name: 'Setup UiPath CLI'
description: 'Setup the UiPath CLI on the runner'

runs:
  using: "composite"
  steps:
    - name: Setup CLI
      shell: pwsh
      run: |
             New-Item -Path "C:\\" -ItemType "directory" -Name "uipathcli";
             Invoke-WebRequest "https://www.myget.org/F/uipath-dev/api/v2/package/UiPath.CLI/1.0.7985.19721" -OutFile "C:\\uipathcli\\cli.zip";
             Expand-Archive -LiteralPath "C:\\uipathcli\\cli.Zip" -DestinationPath "C:\\uipathcli";
      
    - name: Analyze
      shell: pwsh
      run: |
        foreach($package in Get-ChildItem -Path ${{ github.workspace }} -Recurse -Filter project.json -File)
          {
            & "C:\\uipathcli\\lib\\net461\\uipcli.exe" package analyze "$package" --analyzerTraceLevel "Warning" --stopOnRuleViolation
          }
