name: 'UiPath Pack'
description: 'Analyzes and packs all UiPath projects within the repository it runs in. Analyze uses UiPath Workflow Analyzer and will cause the job to stop on Rule Violationes.'

runs:
  using: "composite"
  steps:
    - name: Analyze
      shell: pwsh
      run: |
        foreach($project in Get-ChildItem -Path ${{ github.workspace }} -Recurse -Filter project.json -File)
        {
          & "C:\\uipathcli\\lib\\net461\\uipcli.exe" package analyze "$project" --analyzerTraceLevel "Warning" --stopOnRuleViolation
      #  & "C:\\uipathcli\\lib\\net461\\uipcli.exe" package analyze "$project" --analyzerTraceLevel "Warning" --stopOnRuleViolation --orchestratorUrl "<URL>" --orchestratorTenant <tenant> --orchestratorUsername *** --orchestratorPassword *** --orchestratorFolder "folder_name"
        }
      # run: ${{ github.action_path }}/analyze-uipath-projects.ps1 ${{ github.workspace }}
      
    - name: Pack
      shell: pwsh
      run: ${{ github.action_path }}/pack-uipath-projects.ps1 ${{ github.workspace }}
