name: 'UiPath Pack'
description: 'Analyzes and packs all UiPath projects within the repository it runs in. Analyze uses UiPath Workflow Analyzer and will cause the job to stop on Rule Violationes.'
inputs:
  orchestratorUrl: 
    description: 'Orchestrator instance URL'
    required: true
  orchestratorTenant:
    description: 'Tenant on the Orchestrator instance'
    required: true
  orchestratorFolder:
    description: 'Folder path in modern folder setup'
    required: true
  orchestratorUsername:
    description: 'Account for authenticating to Orchestrator'
    required: true
  orchestratorPassword:
    description: 'Password for the Orchestrator account'
    required: true

runs:
  using: "composite"
  steps:
# --ignoredRules "UI-DBP-030"
# --analyzerTraceLevel "Warning"
    - name: Analyze
      shell: pwsh
      run: |
        $projectList = Get-ChildItem -Path ${{ github.workspace }} -Recurse -Filter project.json -File
        if($projectList.Count -gt 0)
        {
          foreach($project in $projectList)
            {
              & "C:\\uipathcli\\lib\\net461\\uipcli.exe" package analyze "$($project.FullName)" --stopOnRuleViolation --ignoredRules ST-SEC-008 --orchestratorUrl ${{ inputs.orchestratorUrl }} --orchestratorTenant ${{ inputs.OrchestratorTenant }} --orchestratorUsername ${{ inputs.orchestratorUsername }} --orchestratorPassword ${{ inputs.orchestratorPassword }} --orchestratorFolder ${{ inputs.orchestratorFolder }}
            }
        }
        else
        {
          return -1
        }
      
    - name: Pack
      shell: pwsh
      run: ${{ github.action_path }}/pack-uipath-projects.ps1 ${{ github.workspace }}
